### ISSUE TITLE
crash on 'edit'

### ISSUE THREAD

**Issue by zabaat** [juanpasolano/sails-hook-cms#9]
sails 0.12.1
node  5.9.0
windows 10 (also on ubuntu)

clicking edit on a line takes me to the page to edit but immediately crashes server.
very nice looking system by the way!

```
sails> TypeError: Cannot read property 'id' of undefined
    at $b3 (eval at <anonymous> (C:\aCode\poe\server\node_modules\sails-hook-cms
\node_modules\jade-async\lib\jade.js:98:12), <anonymous>:3:776)
    at eval (eval at <anonymous> (C:\aCode\poe\server\node_modules\sails-hook-cm
s\node_modules\jade-async\lib\jade.js:98:12), <anonymous>:3:2219)
    at C:\aCode\poe\server\node_modules\sails-hook-cms\node_modules\promise\core
.js:33:15
    at flush (C:\aCode\poe\server\node_modules\asap\asap.js:27:13)
    at _combinedTickCallback (node.js:376:9)
    at process._tickDomainCallback (node.js:431:11)

```

```
/**
 * Users.js
 */

module.exports = {

  attributes: {
    email:{type:"email"},
    active:{type:"boolean"},
    admin:{type:"boolean"},

  }
};
```

**Comment by adjipramono** [comment]
did someone manage to solve this?
